trigger:
  branches:
    include:
      - main
  paths:
    include:
      - azure_resources/environments/dev.tfvars

parameters:
  - name: "environment"
    displayName: Environment
    default: "dev"
    values:
      - dev
      - prod

variables:
  - group: "infrastructure-variables"

stages:
  #Terraform Stage
  - template: ./templates/terraform-template.yml
    parameters:
      environment: ${{ parameters.environment }} # Azure Pipeline Environment
      state_file_dir: "azure_resources" # State File directory in a storage account
      terraform_dir: "/azure_resources" # Terraform directory
      ${{ if eq(parameters.environment, 'dev') }}:
        service_connection: "PO-DEV-SP" # Azure Service connection
      ${{ else }}:
        service_connection: "PO-PRD-SP" # Azure Service connection
      resource_group: "RG-POSH-WEU-TFSTATE-PRD-01" # Resource group
      storage_account: "stposhweutfstateprd01" # Name of storage account
      agent_pool: "linux-build-agents-dev" # Agent pool name
