---
- name: Download log analytic agent installation file
  ansible.builtin.get_url:
    url: https://github.com/microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_v1.17.2-0/omsagent-1.17.2-0.universal.x64.sh
    dest: /tmp/omsagent.sh
    force: true
    mode: u=rwx,go-rwx

- name: Install log analytic agent
  ansible.builtin.shell: |
    sh /tmp/omsagent.sh --install -w {{ azure_log_agent_workspace_id }} -s {{ azure_log_agent_secret }} --skip-docker-provider-install
    sh /tmp/omsagent.sh --upgrade -p {{ azure_log_agent_proxy_url }} -w {{ azure_log_agent_workspace_id }} -s {{ azure_log_agent_secret }}
  register: install_log_analytic_agent
  changed_when: install_log_analytic_agent.rc != 0

- name: Config proxy for log analytic agent
  ansible.builtin.shell: |
    proxyconf="{{ azure_log_agent_proxy_url }}"
    sudo echo $proxyconf >>/etc/opt/microsoft/omsagent/proxy.conf
    sudo chown omsagent:omiusers /etc/opt/microsoft/omsagent/proxy.conf
    sudo /opt/microsoft/omsagent/bin/service_control restart {{ azure_log_agent_workspace_id }}
  register: config_proxy_log_analytic_agent
  changed_when: config_proxy_log_analytic_agent.rc != 0
