---
- name: Install package for update partition
  ansible.builtin.yum:
    name:
      - cloud-utils-growpart
      - gdisk
  register: packages_installed

- name: Update partition
  ansible.builtin.shell: |
    lsblk
    set -o pipefail
    echo -e "n\n\n\n\nw" | fdisk /dev/sda
    mke2fs -j /dev/sda5
    echo -e "y" | pvcreate /dev/sda5
    vgextend rootvg /dev/sda5
    lvresize -r -l 20%VG /dev/mapper/rootvg-varlv
    lvresize -r -l 80%VG /dev/mapper/rootvg-rootlv
    df -Th /
    df -Th /home
  changed_when:
    - packages_installed.changed # noqa: no-handler
