---
- name: Tranfer scripts
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    mode: "0755"
  loop:
    - src: "templates/create_ansible_account.sh.j2"
      dest: "/tmp/create_ansible_account.sh"
    - src: "templates/create_poadmin_account.sh.j2"
      dest: "/tmp/create_poadmin_account.sh"
  register: copy_script

- name: Execute the script
  ansible.builtin.command: sh {{ item }}
  loop:
    - /tmp/create_ansible_account.sh
    - /tmp/create_poadmin_account.sh
  changed_when: copy_script.changed
  register: executed_script

- name: Remove scripts
  ansible.builtin.command: rm -rf {{ item }}
  loop:
    - /tmp/create_ansible_account.sh
    - /tmp/create_poadmin_account.sh
  changed_when: executed_script.changed
