---
- name: Check if apache-maven exists or not
  ansible.builtin.stat:
    path: /opt/{{ maven_package }}
  register: apache_maven_installed

- name: Maven is install
  ansible.builtin.debug:
    msg: "{{ maven_package }} is exists"
  when: apache_maven_installed.stat.exists

- name: Maven is not installed
  ansible.builtin.debug:
    msg: "{{ maven_package }} doesn't exists"
  when: not apache_maven_installed.stat.exists

- name: Downloading maven packages
  ansible.builtin.get_url:
    url: "{{ maven_url }}"
    dest: /opt
    mode: '0755'
  when: not apache_maven_installed.stat.exists

- name: Extract packages
  ansible.builtin.unarchive:
    src: /opt/{{ maven_package }}-bin.tar.gz
    dest: /opt
    remote_src: true
  when: not apache_maven_installed.stat.exists

- name: Change permissions on apache maven file
  ansible.builtin.file:
    path: /opt/{{ maven_package }}
    mode: '0755'
    recurse: true
  when: not apache_maven_installed.stat.exists
  check_mode: false
