---
- name: Restart postgresql
  become: true
  ansible.builtin.systemd:
    name: "postgresql.service"
    daemon_reload: true
    state: "restarted"
    enabled: true
  loop: "{{ ansible_play_hosts }}"
  delegate_to: "{{ item }}"
  changed_when: false
  failed_when: false
